# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Contatinhos #pythonbr14"
tagline: Bora conhecer a galera do BrejaTec?<br/>Encontre seus coleguinhas aqui 😉
author: pBaesse
email: pbaesse@gmail.com
baseurl: "/BrejaTec-Contatos" # the subpath of your site, e.g. /blog
url: "https://pbaesse.net" # the base hostname & protocol for your site

collections:
  contatinhos:
    output: true

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

theme: jekyll-theme-cayman
